wordPopperApp/config/routes.rb
Rails.application.routes.draw do
  resources :lines
  resources :users
  root "sessions#new"
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get     'myprofile' => 'users#show'
end

wordPopperApp/app/models/line.rb
class Line < ActiveRecord::Base
  has_and_belongs_to_many :users;
  validates :line, presence: true, length: {maximum: 30}
end

wordPopperApp/app/models/user.rb
class User < ActiveRecord::Base
  has_many :lines
  validates :username, presence: true, length: {maximum: 50}, uniqueness: true
  has_secure_password
  validates :password, presence: true
end

wordPopperApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :authenticate

   def authenticate
     unless logged_in?
       flash[:error] = "You must be logged in to access this section of the site"
       redirect_to login_path
     end
   end

end

wordPopperApp/app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = current_user.lines.build(line_params)

    respond_to do |format|
      if @line.save
        @user = User.find(session[:user_id])
        format.html { redirect_to @user, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }

      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        @user = User.find(session[:user_id])
        format.html { redirect_to @user, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @user = User.find(session[:user_id])
    @line.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:line)
    end
end

wordPopperApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new,:create]
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid username/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

wordPopperApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate

  def index
  end

  def about
  end

  def contact
  end
end

wordPopperApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:new,:create,:show]
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    if logged_in?

      @user = User.find(session[:user_id])
      @users = User.includes(:line)
      @line = Line.new
      @lines = Line.all
    #  if  @user.roles.find{|role| role=='administrator'}
    #   end
    else
      redirect_to login_path
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Welcome to Randomizer"
      redirect_to @user
    else
      render new_user_path
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

wordPopperApp/app/helpers/application_helper.rb
module ApplicationHelper
end

wordPopperApp/app/helpers/lines_helper.rb
module LinesHelper
end

wordPopperApp/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
    if @current_user.nil?
    @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

wordPopperApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Randomizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Comfortaa:400,300' rel='stylesheet' type='text/css'>
</head>
<body>
  <% if logged_in? %>
  <div id="logout">
    <%= button_to 'Logout', logout_path, :method => :delete %>
  </div>
  <% end %>
  <%= yield %>
</body>
</html>

wordPopperApp/app/views/lines/_form.html.erb
<%= form_for (@line) do |f| %>

  <h3>Add a new Line: </h3>
  <div class="field">
    <%= f.text_field :line %>
  </div>
  <div class="actions"> Copy and Paste Saved Lines: 
    <%= f.submit 'Save Line' %>
  </div>
<% end %>

wordPopperApp/app/views/lines/_list.html.erb
<div class="new-line">
  <% @lines.each do |line| %>
    <tr>
      <td><%= line.line %></td>
      <td><%= link_to 'Show', line %></td>
      <td><%= link_to 'Edit', edit_line_path(line) %></td>
      <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

</div>

wordPopperApp/app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form' %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', user_path %>

wordPopperApp/app/views/lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lines</h1>

<table>
  <thead>
    <tr>
      <th>Line</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.line %></td>
        <td><%= link_to 'Show', line %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

wordPopperApp/app/views/lines/new.html.erb
<h1>New Line</h1>

<%= render 'form' %>

<%= link_to 'Back', lines_path %>

wordPopperApp/app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line:</strong>
  <%= @line.line %>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>

wordPopperApp/app/views/users/index.html.erb
<div id="user-page">


    <h1>You can't see all the users</h1>
    <p>Already A Member?</p>
    <%= label_tag :username %>:
    <%= text_field_tag :username %>
    <br>
    <%= label_tag :password %>:
    <%= password_field_tag :password %>
    <br><br>
    <%= submit_tag "Login"%>
</div>

wordPopperApp/app/views/users/new.html.erb
<%= form_for @user, :html => {:class => "container"} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <%= f.label :username, "Username: "%>
    <%= f.text_field :username%>
    <%= f.label :password, "Password: "%>
    <%= f.password_field :password%>
    <%= f.label :password_confirmation, "Confirm Password"%>
    <%= f.password_field :password_confirmation%>
    <%= f.submit%>
    <% end %>
    <p>Already A Member?</p>
    <%= label_tag :username %>:
    <%= text_field_tag :username %>
    <br>
    <%= label_tag :password %>:
    <%= password_field_tag :password %>
    <br><br>
    <%= submit_tag "Login"%>
  </div>

wordPopperApp/app/views/users/show.html.erb
<div id="user-page">

      <%=button_to 'DELETE ACCOUNT', @user, :method => :delete %>
      <h1>Ready Player: <%= @user.username%></h1>

      <h1>Let's Explode Some Letters</h1>

      <div id="emoji-container">

      </div>
      <button class="selector">POP Current Line</button>
      <div id="lines-container">

      <%= render partial: 'lines/form' %>
      <%= render partial: 'lines/list' %>
      </div>
</div>